package br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp;

/**
* br/edu/ifpb/pos/ativ/corba/client/idl/HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/edu/ifpb/pos/ativ/corba/client/idl/HelloApp.idl
* Segunda-feira, 16 de Outubro de 2017 13h02min12s BRT
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp.HelloHelper.type ();
  }

}
