package br.edu.ifpb.pos.ativ.corba.client.idl.HelloApp;


/**
* br/edu/ifpb/pos/ativ/corba/client/idl/HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/edu/ifpb/pos/ativ/corba/client/idl/HelloApp.idl
* Segunda-feira, 16 de Outubro de 2017 13h02min12s BRT
*/

public interface HelloOperations 
{
  String helloworld ();
  void shutdown ();
} // interface HelloOperations
